#!/bin/bash
#
# initd-example      Node init.d 
#
# chkconfig: 345 80 20
# description: Clabie server
# processname: clabie-server
#

# Source function library.
. /lib/lsb/init-functions

user=clabie
NAME=clabie-server                               # Unique name for the application
INSTANCE_DIR=/home/$user/l4c.me                  # Location of the application source
SOURCE_NAME=$INSTANCE_DIR/app.js                 # Name os the applcation entry point script
FOREVER_ID=$INSTANCE_DIR/scripts/forever-id.js   # Node.js script used to check for the status of the process and return the forever id

pidfile=/var/run/$NAME.pid
logfile=/var/log/$NAME.log
outfile=$INSTANCE_DIR/logs/output.log
errfile=$INSTANCE_DIR/logs/error.log
forever_dir=/var/run/forever       # Forever root directory.

node=node
forever=forever
awk=awk
sed=sed


start() {
    echo "Starting $NAME node instance: "

    if [ "$id" = "" ]; then
        # Create the log and pid files, making sure that the target use has access to them
        touch $logfile
        chown $user $logfile

        touch $pidfile
        chown $user $pidfile

	touch $outfile
	chown $user $outfile

	touch $errfile
	chown $user $errfile

        # Launch the application
        start_daemon
            # $forever start -p $forever_dir --pidfile $pidfile -l $logfile -a -d $SOURCE_NAME
            $forever start -p $forever_dir --pidFile $pidfile -a -l $logfile -o $outfile -e $errfile $SOURCE_NAME
	RETVAL=$?
    else
        echo "Instance already running"
        RETVAL=0
    fi
}


restart() {
    echo -n "Restarting $NAME node instance : "
    if [ "$id" != "" ]; then
        $forever restart -p $forever_dir $id
        RETVAL=$?
    else
        start
    fi
}


stop() {
    echo -n "Shutting down $NAME node instance : "
    if [ "$id" != "" ]; then
        $forever stop -p $forever_dir $id
    else
        echo "Instance is not running";
    fi
    RETVAL=$?
}


getForeverId() {
    # local pid=$(pidofproc -p $pidfile)
    pid=`cat $pidfile`
    if [ "$pid" != "" ]; then
        $node $FOREVER_ID $forever_dir $pidfile $SOURCE_NAME
        # echo "$tmp";
        # echo "$SOURCE_NAME";
    fi;
    # RETVAL=$?
    # $forever list -p $forever_dir | $sed -e 's/\x1b\[[0-9; ]*m//g' | $awk "\$4 == \"$pid]\" { gsub(/[\[\]]/, \"\", \$1); print \$1; }"
    # echo `./home/clabie/test/forever_id.js $forever_dir $pidfile`
}

id=$(getForeverId)
# echo "id:$id"


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status -p ${pidfile}
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac

exit $RETVAL
